// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV5ebmXMXbWLbzBw6m2N8t7dEQ-Pn2EXw',
    appId: '1:849683509601:web:6e9d4b2949cdb42db89520',
    messagingSenderId: '849683509601',
    projectId: 'blooddonationapp-389c4',
    authDomain: 'blooddonationapp-389c4.firebaseapp.com',
    storageBucket: 'blooddonationapp-389c4.appspot.com',
    measurementId: 'G-NJH48ES5TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMsdFNmhaDlBZWRax5Rozq6tnHY1ndMc',
    appId: '1:849683509601:android:dfe22182f66522a9b89520',
    messagingSenderId: '849683509601',
    projectId: 'blooddonationapp-389c4',
    storageBucket: 'blooddonationapp-389c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7ksq_paHdV8IQA-2Y7rebWp1fs4Lq9Q',
    appId: '1:849683509601:ios:b6759d09567bbe35b89520',
    messagingSenderId: '849683509601',
    projectId: 'blooddonationapp-389c4',
    storageBucket: 'blooddonationapp-389c4.appspot.com',
    iosBundleId: 'com.example.facultyreservation',
  );
}
